# Generated by Django 5.0 on 2024-07-12 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('entreprise', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('ouverture', models.CharField(max_length=10)),
                ('fermeture', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact', models.CharField(max_length=20)),
                ('pharmacien', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pharmacy_images/')),
                ('assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacies.assurance')),
            ],
        ),
    ]
