# Generated by Django 5.0 on 2024-07-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='pharmacien',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
