# Generated by Django 5.0 on 2024-06-06 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='assurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('pourcentage', models.IntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('horaire', models.DateTimeField()),
                ('est_de_garde', models.BooleanField(default=False)),
                ('etoiles', models.IntegerField()),
                ('images', models.ImageField(upload_to='pharmacies/')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('assurances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.assurance')),
                ('le_pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.pays')),
            ],
        ),
        migrations.CreateModel(
            name='produits_pharmaceutiques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('addresse', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('prix', models.IntegerField()),
                ('dosage', models.CharField(max_length=100)),
                ('posologie', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='medicaments/')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('assurances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_pharmaceutiques', to='apps.assurance')),
                ('la_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_pharmaceutiques', to='apps.categorie')),
                ('la_pharmacies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_pharmaceutiques', to='apps.pharmacies')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('profile_photo', models.ImageField(upload_to='profile_photo/')),
                ('bio', models.TextField()),
                ('poste', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('le_pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville', to='apps.pays')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='villes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.ville'),
        ),
    ]
